name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - pre-*
      - V2.*
      - draft-*

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
jobs:
  tagged-release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Secret setup
        env:
          GOOG_CREDS_DEV: "${{secrets.GOOG_CREDS_DEV}}"
          GOOG_CREDS_PROD: "${{secrets.GOOG_CREDS_PROD}}"
          GRADLE_PROPS: "${{secrets.GRADLE_PROPS}}"
        run: ./config/github_secrets.sh

      - name: Firebase config
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon --build-cache firebase

      - name: Build all release artifacts - assembleRelease
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --parallel --no-daemon clean assembleRelease

      - name: Changelog
        run: ./config/gen_changelog.sh

      - name: Github Release creation
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/V')
        with:
          body_path: release_notes.md
          files: |
            **/*.apk
            platform-sdk/build/outputs/**/*.aar
            ./app/build/outputs/mapping/release/mapping.txt

      - name: Github Draft Release creation
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/draft-')
        with:
          body_path: release_notes.md
          files: |
            **/*.apk
            platform-sdk/build/outputs/**/*.aar
            ./app/build/outputs/mapping/release/mapping.txt
          draft: true

      - name: Build staging mdm for setuptool publishing
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --parallel --no-daemon -Porg.gradle.caching=false clean assembleStaging
      
      # Add Staging apk to previously created release
      - name: Github Release edition - Add staging apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/V')
        with:
          body_path: release_notes.md
          files: |
            **/*.apk
            platform-sdk/build/outputs/**/*.aar

      - name: Github Draft Release edition - Add staging apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/draft-')
        with:
          body_path: release_notes.md
          files: |
            **/*.apk
            platform-sdk/build/outputs/**/*.aar
          draft: true
