name: Debug builds on PR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build all debug flavors
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon --parallel --build-cache assembleDebug
