name: Lint static analysis on PR

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: lint check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon --parallel lint
